PROCESSES_NUM = 4

MAX_SPEECH_FILES = 600
MAX_NOISE_FILES = 900

FILES_PER_STEP = 30

MUSAN_PATH = '/home/kript0n/Documents/musan'
SPEECH_PATH = [MUSAN_PATH + '/speech/librivox', MUSAN_PATH + '/speech/us-gov']
NOISE_PATH = [MUSAN_PATH + '/noise/sound-bible', MUSAN_PATH + '/noise/free-sound']

MUSAN_DATASET = 0
TEDLIUM_DATASET = 1

DATASET_PATH = './dataset/datasets'
VOICED_FNAME = DATASET_PATH + '/voiced.csv'
UNVOICED_FNAME = DATASET_PATH + '/unvoiced.csv'

FRAME_SIZE = 400
FRAME_STEP = 160
LOW_HZ = 300
HIGH_HZ = 8000
FILTERBANKS_NUM = 26
MFCC_NUM = 13
FFT_N = 512
NONE_VOICED = 0
VOICED = 1

VOICED_FEATURES_NUM = 4500000
UNVOICED_FEATURES_NUM = 2000000

TRAIN_TEST_RATIO = 0.75
TRAIN_VALIDATION_RATIO = 0.75
